#!/bin/sh

zipfiles=`git diff HEAD --name-only | grep -E '.zip' | sed -e 's/\.zip$//'`

for file in $zipfiles; do
  if [[ -f $file.zip ]]; then
    if [ -d "${file}-output" ] ; then
      rm -r $file-output
    fi

    if [ -d "${file}-unpack" ] ; then
      rm -r $file-unpack
    fi

    echo "extracting resources from ${file}.zip"
    ./migrate-backup.sh $file.zip
    git add $file-unpack
    git add $file-output
  else
    if [ -d "${file}-output" ] ; then
      rm -r $file-output
      git rm -r $file-output
    fi

    if [ -d "${file}-unpack" ] ; then
      rm -r $file-unpack
      git rm -r $file-unpack
    fi
  fi
done

yamlfiles=`git diff HEAD --name-only | grep -E '.yaml'`

for file in $zipfiles; do
  if [[ -f $file ]]; then
    echo "${file}-added"
  else
    echo "${file}-deleted"
  fi
done