#!/bin/sh

zipfiles=`git diff HEAD --name-only | grep -E '.zip' | sed -e 's/\.zip$//'`

for file in $zipfiles; do
  if [[ -f $file.zip ]]; then
    if [ -d "${file}" ] ; then
      rm -r $file
    fi

    echo "extracting resources from ${file}.zip"
    ./migrate-backup.sh $file.zip
    git add $file
    ./migrate-backup-dps.sh $file > ./$file/$file-dps.yaml
    ./migrate-backup-service.sh $file 8001 > ./$file/$file-service.yaml
    ./migrate-backup-route.sh $file > ./$file/$file-route.yaml
  else
    if [ -d "${file}" ] ; then
      rm -r $file
      git rm -r $file
    fi
  fi
done

yamlfiles=`git diff HEAD --name-only | grep -E '.yaml'`

cd ..

for file in $yamlfiles; do
  if [[ -f "./datapower-operator-scripts/${file}" ]]; then
    if [[ "$file" == *-dps* ]]; then
      yes | cp -f "./datapower-operator-scripts/${file}" ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/
      echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/${file} created"
    elif [[ "$file" == *-service* ]]; then
      yes | cp -f "./datapower-operator-scripts/${file}" ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/
      echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/${file} created"
    elif [[ "$file" == *-route* ]]; then
      yes | cp -f "./datapower-operator-scripts/${file}" ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/
      echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/${file} created"
    elif [[ "$file" == *default* ]]; then
      array=($(echo "$file" | tr '/' '\n'))
      yes | cp -f "./datapower-operator-scripts/${file}" "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[2]}"
      echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[2]} created"
    fi
  else
    if [[ "$file" == *-dps* ]]; then
      if [[ -f "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/${file}" ]]; then
        rm "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/${file}"
        echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/${file} deleted"
      fi
    elif [[ "$file" == *-service* ]]; then
      if [[ -f "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/${file}" ]]; then
        rm "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/${file}"
        echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/${file} deleted"
      fi
    elif [[ "$file" == *-route* ]]; then
      if [[ -f "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/${file}" ]]; then
        rm "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/${file}"
        echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/${file} deleted"
      fi
    elif [[ "$file" == *default* ]]; then
      array=($(echo "$file" | tr '/' '\n'))
      if [[ -f "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[2]}" ]]; then
        rm "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[2]}"
        echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[2]} deleted"
      fi
    fi 
  fi
done
