#!/bin/sh

zipfiles=`git diff HEAD --name-only | grep -E '.zip' | sed -e 's/\.zip$//'`

for file in $zipfiles; do
  if [[ -f $file.zip ]]; then
    if [ -d "${file}" ] ; then
      rm -r $file
    fi

    if [ -d "${file}-unpack" ] ; then
      rm -r $file-unpack
    fi

    echo "extracting resources from ${file}.zip"
    ./migrate-backup.sh $file.zip
    git add $file-unpack
    git add $file
  else
    if [ -d "${file}" ] ; then
      rm -r $file
      git rm -r $file
    fi

    if [ -d "${file}-unpack" ] ; then
      rm -r $file-unpack
      git rm -r $file-unpack
    fi
  fi
done

yamlfiles=`git diff HEAD --name-only | grep -E '.yaml'`
echo $yamlfiles

cd ..

for file in $yamlfiles; do
  if [[ -f "./datapower-operator-scripts/${file}" ]]; then
    if [[ "$file" == *-dps* ]]; then
      yes | cp -f "./datapower-operator-scripts/${file}" ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/
      echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/${file} created"
    elif [[ "$file" == *-service* ]]; then
      yes | cp -f "./datapower-operator-scripts/${file}" ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/
      echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/${file} created"
    elif [[ "$file" == *-route* ]]; then
      yes | cp -f "./datapower-operator-scripts/${file}" ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/
      echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/${file} created"
    elif [[ "$file" == *default* ]]; then
      array=($(echo "$file" | tr '/' '\n'))
      echo $array[0]
      echo $array[1]
      yes | cp -f "./datapower-operator-scripts/${array[0]}-${array[1]}" ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/
      echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${file} created"
    fi
  else
    if [[ "$file" == *-dps* ]]; then
      if [[ -f "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/${file}" ]]; then
        rm "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/${file}"
        echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/${file} deleted"
      fi
    elif [[ "$file" == *-service* ]]; then
      if [[ -f "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/${file}" ]]; then
        rm "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/${file}"
        echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/${file} deleted"
      fi
    elif [[ "$file" == *-route* ]]; then
      if [[ -f "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/${file}" ]]; then
        rm "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/${file}"
        echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/${file} deleted"
      fi
    elif [[ "$file" == *default* ]]; then
      array=($(echo "$file" | tr '/' '\n'))
      echo $array[0]
      echo $array[1]
      if [[ -f "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[1]}" ]]; then
        rm "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[1]}"
        echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[1]} deleted"
      fi
    fi 
  fi
done
