apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: migration-example
spec:
  replicas: 1
  version: 10.0-cd
  license:
    accept: true
    use: nonproduction
    license: L-RJON-CCCP46
  users:
  - name: admin
    accessLevel: privileged
    passwordSecret: datapower-user
  domains:
    - name: default
      certs:
      - certType: usrcerts
        secret: datapower-cert
      dpApp:
        config:
        - default-cfg
        local:
        - default-local