apiVersion: v1
binaryData:
  default-local.tar.gz: H4sIABXDc2MAA+2V32/aMBDHeeavyF9ACITkYdoDCu1Uteuihkp7QyY5wKpjR7bTCU3932fnB4SprKItm6rdR0KGy/l757tzGLi9szM0hJOJXb0w8LprS8/zx2M/9IfhyPh53iT0e87k/Kn1eqXSRDpOr1iXXJeyPOb30vMPysBlJSeLVPAVXZ9pFk7vvz8Mhtj/v8Fh/6ON3CotHujAGt4rhm1wYHp8pP+jwP+9/0Fo3J3heyXwJ/7z/u86PnI+Oz/7juPc0OX97dV389MVhXbpMnczokkhfoB0SyVdRVbAQVeDkzIK3HylS/uJ5LaotAZKfOpoBf6b1BaBXwk+9fs3xqtJdAYrUjI9pzl8K7UxTqppsnHji5k1i1J7xu7t7J0H9rijZzaMW7s1X8O2IFR+Ab6PMgp3uyImOOXrSOQ54dneZbz3OHgUQ5aAdQibCOZAEZHZHZAMZHOsO8iFhmajzb5y+0pV2jjEF17oBxecLBlYh/pkcyGYmlF5UqGXlNdlIVJTTQWPBaPpdg55wYiGmOjN83qZNKUyKxMpYQdvEOvjFq3eoqgEF7pRVHU4aU6Yasimpd6YPGhKquAm3CUj60QTXar6ZE9Vx5OpqbXNuJ3RO0iBPkLTs27LnCS5iapULimDU6thnIErxQYpX1VqddhY0kczC8cV23ooSEsJNkAKUiu3oxEZwysFEpCPIKPp6dvrzpivbr17UEBeSd6C3lXUqwcoiq8BiikzdW3HLqnknLk0L0kza9GGcA6sbUItMBcPwM09f80NT8Sq3t++L3aGo5N8fPLqZWbnT1uJTu2vMjtlmsLxG/LCRNd5L+hO6PDevD3A/sp0Yzz1//X/A4IgCIIgCIIgCIIgCIIgCIIgCIIgH4df5JGYDAAoAAA=
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: default-local
  annotations: 
    argocd.argoproj.io/sync-wave: "335"
