apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "350"
  name: deploy-generic-11152022-instance
spec:
  replicas: 3
  version: 10.0-cd
  license:
    accept: true
    use: nonproduction
    license: L-RJON-CCCP46
  users:
  - name: admin
    accessLevel: privileged
    passwordSecret: datapower-user
  domains:
    - name: default
      dpApp:
        config:
        - default-cfg
        local:
        - default-local
      #certs:
      #- certType: usrcerts
        #secret: default-certs
      #- certType: sharedcerts
        #secret: default-sharedcerts
    - name: generic
      dpApp:
        config:
        - generic-cfg
        local:
        - generic-local
      certs:
      - certType: usrcerts
        secret: soaws3vs01-priv-key-privkey
      - certType: sharedcerts
        secret: datapowervs01apisoaair4c-812eb57-sscert
      - certType: sharedcerts
        secret: sco-sitescope-vstest-0000573-sscert

