apiVersion: v1
binaryData:
  default-local.tar.gz: H4sIAIt7YWMAA+1V247aMBDlma/IF5ALSXio+oACW612u402VOobMskErHXsyHa2QtX+e31JArTLVuylVVtGQg6T8ZmZc8bOyB28uXmeN4kix6yxXb0gtGtrjh+Og9Dzxt7Edzx/PI6jgRO9fWmDQSMk4qqUGkmO87sVUApS/hynwsryCZy2j379S2zkkoaiZc5oiddvNAun6x/FkX/W/3fYof7Jhm+FZHd4pB2vlUPxEbfUPKZ/EIc/6B944UTp771WAU/Zf65/r3jgvHe+DR3HucarzzeXX9Rfl9XSxavKLZBENfsK3G0EdwUqQXFkBicnGKh6xCv9S/i2Nlgjwd7tYcXhi9CWcWgAH4bDaxXVFjqDEjVELnAFnxqpnJFhXudN5zPtZo30ld/v/XsvdLvBIxvGnV+7r2BbI8w/AN1lCSb9roQwiuk6YVWFaLELGe8iDl6lUGSgAyZtBtVQgnhxC6gA3rZ1CxWT0G7U1Zuwj1jkbUA69ydhPKdoRUAH2M4WjBExw/wkoleYWloQl1hiRlNGcL5dQFUTJCFFcvM4XsEVVWolLEfk4AbRMW7d4S1rA7iULaKw6bjqMJdQTBu5UXXgHJnkKt0FQetMItkI29mDUTybKq51xd2M3kIO+B5azfYlc7LsOjGlXGACp7KhgoEKQUY5LQ2aTZtyfK9m4Thix4eAvOGgE+TApXD3MBLleCZABvweeDI9fbtVRj26dveohspA3oDsGfXtACXpFUA9JYrXbuwyA+csuLok1awlG6QuR9KJYAEW7A6oOufPOeEZK+3+7r7oHUcn+fjk2WWm509qiD3uLws9ZRLD8RPyi4m2dS9xD3R4bl6eYHdk9nM8DP/09+FsZzvbv2vfAfQKJJsAEAAA
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: default-local
  annotations: 
    argocd.argoproj.io/sync-wave: "335"
