apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "350"
  name: generic-instance
spec:
  replicas: 1
  version: 10.0-cd
  license:
    accept: true
    use: nonproduction
    license: L-RJON-CCCP46
  users:
  - name: admin
    accessLevel: privileged
    passwordSecret: datapower-user
  domains:
    - name: {generic}
      #certs:
      #- certType: usrcerts
        #secret: {generic}-cert
      dpApp:
        config:
        - {generic}-cfg
        local:
        - {generic}-local
